#include <stdint.h>
#include <stdbool.h>
#include "inc/tm4c123gh6pm.h"
#include "inc/hw_memmap.h"
#include "inc/hw_types.h"
#include "driverlib/sysctl.h"
#include "driverlib/interrupt.h"
#include "driverlib/gpio.h"
#include "driverlib/timer.h"


/*
 * main.c
 */
int main(void) {
	uint32_t ui32Period;

	//Enable GPIO clock
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
	//Configure GPIO pins as output
	GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3);

	//Set the system clock to 40MHz. 16MHz Main -> 400MHz PLL -> divide by 10
	SysCtlClockSet(SYSCTL_SYSDIV_5|SYSCTL_USE_PLL|SYSCTL_XTAL_16MHZ|SYSCTL_OSC_MAIN);

	//Enables peripherals to operate and respond to read/writes
	SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0);
	//Configure Timer 0 to be a concatenated 32-bit periodic timer
	TimerConfigure(TIMER0_BASE, TIMER_CFG_PERIODIC);

	//compute the period of interrupts generated by Timer0 in terms of system clock cycles
	ui32Period = (SysCtlClockGet() / 10) / 2;

	//Set the interrupt period-1 as the max count for the timer
	TimerLoadSet(TIMER0_BASE, TIMER_A, ui32Period -1);

	//enables TIMER0 to generate interrupts in the NVIC
	IntEnable(INT_TIMER0A);
	//sets TIMER0 to generate an interrupt when it times out
	TimerIntEnable(TIMER0_BASE, TIMER_TIMA_TIMEOUT);
	//Enables the processor to respond to interrupts
	IntMasterEnable();

	//Start the timer
	TimerEnable(TIMER0_BASE, TIMER_A);

	//Empty main loop, this example only shows the ISR
	while(1)
	{
	}

}

void Timer0IntHandler(void)
{
	// Clear the timer interrupt
	TimerIntClear(TIMER0_BASE, TIMER_TIMA_TIMEOUT);

	// Read the current state of the GPIO pin (blue LED) and
	// write back the opposite state
	if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_2))
	{
		GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3, 0);
	}
	else
	{
		GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 4);
	}

}
